// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF5iYvcCAOBcVaDP-R8fK3tFiGFO3cMXs',
    appId: '1:149217387522:web:06003d4271e4cb9dadf31b',
    messagingSenderId: '149217387522',
    projectId: 'fasum-1bfcb',
    authDomain: 'fasum-1bfcb.firebaseapp.com',
    storageBucket: 'fasum-1bfcb.firebasestorage.app',
    measurementId: 'G-ECFW080Z50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEkZ265hD-U9n-pATzPm93AL6v8dttS88',
    appId: '1:149217387522:android:bfd21bc47f67048cadf31b',
    messagingSenderId: '149217387522',
    projectId: 'fasum-1bfcb',
    storageBucket: 'fasum-1bfcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpOUnF5RlBbEVFTfInb2grJW4unTPRyjU',
    appId: '1:149217387522:ios:7c15a075fd6ad9f5adf31b',
    messagingSenderId: '149217387522',
    projectId: 'fasum-1bfcb',
    storageBucket: 'fasum-1bfcb.firebasestorage.app',
    iosClientId: '149217387522-q82mt754ja7s5l4jvdjdm910lu9lcu0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpOUnF5RlBbEVFTfInb2grJW4unTPRyjU',
    appId: '1:149217387522:ios:7c15a075fd6ad9f5adf31b',
    messagingSenderId: '149217387522',
    projectId: 'fasum-1bfcb',
    storageBucket: 'fasum-1bfcb.firebasestorage.app',
    iosClientId: '149217387522-q82mt754ja7s5l4jvdjdm910lu9lcu0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF5iYvcCAOBcVaDP-R8fK3tFiGFO3cMXs',
    appId: '1:149217387522:web:c1adb6ab5dacb399adf31b',
    messagingSenderId: '149217387522',
    projectId: 'fasum-1bfcb',
    authDomain: 'fasum-1bfcb.firebaseapp.com',
    storageBucket: 'fasum-1bfcb.firebasestorage.app',
    measurementId: 'G-7PF50H6YD1',
  );

}