// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5oVbUpKjNPokPXF1HjTMBZUy3BpndfH4',
    appId: '1:615560020635:web:67bfd207e9679c2eec3c3e',
    messagingSenderId: '615560020635',
    projectId: 'fasum-1c1b3',
    authDomain: 'fasum-1c1b3.firebaseapp.com',
    databaseURL: 'https://fasum-1c1b3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-1c1b3.firebasestorage.app',
    measurementId: 'G-TLBZZ3DPV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAPwt5i5DMV2LFjwi98JuAAsrBgAgCU84',
    appId: '1:615560020635:android:5d3fdc4a57b41534ec3c3e',
    messagingSenderId: '615560020635',
    projectId: 'fasum-1c1b3',
    databaseURL: 'https://fasum-1c1b3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-1c1b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsBWH-Rjph8ULVDK2EIAU6hFvxZ_-Auuk',
    appId: '1:615560020635:ios:36df2707b3451a93ec3c3e',
    messagingSenderId: '615560020635',
    projectId: 'fasum-1c1b3',
    databaseURL: 'https://fasum-1c1b3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-1c1b3.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsBWH-Rjph8ULVDK2EIAU6hFvxZ_-Auuk',
    appId: '1:615560020635:ios:36df2707b3451a93ec3c3e',
    messagingSenderId: '615560020635',
    projectId: 'fasum-1c1b3',
    databaseURL: 'https://fasum-1c1b3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-1c1b3.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5oVbUpKjNPokPXF1HjTMBZUy3BpndfH4',
    appId: '1:615560020635:web:af818567cce164b0ec3c3e',
    messagingSenderId: '615560020635',
    projectId: 'fasum-1c1b3',
    authDomain: 'fasum-1c1b3.firebaseapp.com',
    databaseURL: 'https://fasum-1c1b3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-1c1b3.firebasestorage.app',
    measurementId: 'G-ERLVF1ENY9',
  );

}