// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP_wSMLH4xv_X1q7goEJ7u_agm380c3-k',
    appId: '1:259084684100:web:c6ac053edd01e8aefd6511',
    messagingSenderId: '259084684100',
    projectId: 'latihanuts-46f0b',
    authDomain: 'latihanuts-46f0b.firebaseapp.com',
    databaseURL: 'https://latihanuts-46f0b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanuts-46f0b.firebasestorage.app',
    measurementId: 'G-5Z3LD1PNGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV1F3aZDHZmLUr6WhlBOuWYrU0nD7NwpY',
    appId: '1:259084684100:android:4f1b67c5a7e2dd71fd6511',
    messagingSenderId: '259084684100',
    projectId: 'latihanuts-46f0b',
    databaseURL: 'https://latihanuts-46f0b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanuts-46f0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATkOlIc48wmiy3T9JINp-CzvG0D1i9UoM',
    appId: '1:259084684100:ios:20c9bc7abc6d3b8dfd6511',
    messagingSenderId: '259084684100',
    projectId: 'latihanuts-46f0b',
    databaseURL: 'https://latihanuts-46f0b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanuts-46f0b.firebasestorage.app',
    iosBundleId: 'com.example.belanja2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATkOlIc48wmiy3T9JINp-CzvG0D1i9UoM',
    appId: '1:259084684100:ios:20c9bc7abc6d3b8dfd6511',
    messagingSenderId: '259084684100',
    projectId: 'latihanuts-46f0b',
    databaseURL: 'https://latihanuts-46f0b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanuts-46f0b.firebasestorage.app',
    iosBundleId: 'com.example.belanja2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP_wSMLH4xv_X1q7goEJ7u_agm380c3-k',
    appId: '1:259084684100:web:c18c4dd7026b4e16fd6511',
    messagingSenderId: '259084684100',
    projectId: 'latihanuts-46f0b',
    authDomain: 'latihanuts-46f0b.firebaseapp.com',
    databaseURL: 'https://latihanuts-46f0b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanuts-46f0b.firebasestorage.app',
    measurementId: 'G-KCNXC8SGM5',
  );
}
