// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT9CWJ1qlKQFjnfknPcQ90h9S1XTAmbnk',
    appId: '1:246003235438:web:c5774bd8013dd5c1cb047f',
    messagingSenderId: '246003235438',
    projectId: 'first-app-a291a',
    authDomain: 'first-app-a291a.firebaseapp.com',
    databaseURL: 'https://first-app-a291a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-a291a.firebasestorage.app',
    measurementId: 'G-249DTEC0Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2SEUWPrDQ0IdJ0oB7QAZCAmpizpoM1CM',
    appId: '1:246003235438:android:542a86247c1a86ebcb047f',
    messagingSenderId: '246003235438',
    projectId: 'first-app-a291a',
    databaseURL: 'https://first-app-a291a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-a291a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNe1VlxHxcgw2XgvAMqLh4_-exx3j8YBA',
    appId: '1:246003235438:ios:c6d4428eae30fbedcb047f',
    messagingSenderId: '246003235438',
    projectId: 'first-app-a291a',
    databaseURL: 'https://first-app-a291a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-a291a.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNe1VlxHxcgw2XgvAMqLh4_-exx3j8YBA',
    appId: '1:246003235438:ios:c6d4428eae30fbedcb047f',
    messagingSenderId: '246003235438',
    projectId: 'first-app-a291a',
    databaseURL: 'https://first-app-a291a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-a291a.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT9CWJ1qlKQFjnfknPcQ90h9S1XTAmbnk',
    appId: '1:246003235438:web:4916b89fb1871e1fcb047f',
    messagingSenderId: '246003235438',
    projectId: 'first-app-a291a',
    authDomain: 'first-app-a291a.firebaseapp.com',
    databaseURL: 'https://first-app-a291a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-a291a.firebasestorage.app',
    measurementId: 'G-JQR1SY7P4J',
  );

}